server:
  port: 8002

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/auth-api?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false